---
title: "Growth curves of all strains with Loperamide"
author: "Rebecca Stevick"
output:
  html_document:
    toc: true
    keep_md: TRUE
    theme: "cerulean"
    toc_float:
      collapsed: false
      smooth_scroll: false
---

Growth curves of bacteria in rich media with Loperamide


## Load Libraries

```{r libraries, message=FALSE, warning=FALSE, results = FALSE}

library("tidyverse")
library("janitor")
library("lubridate")
library("ggpubr")
library("ggtext")
library("patchwork")

theme_set(theme_pubr())
```


## Read in files and data

```{r loaddata, message=FALSE, warning=FALSE}

# second experiment with flavo too. note there are TYES blanks here.
platedata2 <- readxl::read_xlsx("LoperamideGrowthCurves_20210407.xlsx", 
                                range="A34:AP132", sheet = "data", col_names = FALSE) %>% 
   t(.) %>% as.data.frame() %>% setNames(.[1,]) %>% slice(-1) %>% 
   gather(key="well", value="value", A1:H12) %>% add_column(Assay = "2")

platemap2 <- readxl::read_xlsx("LoperamideGrowthCurves_20210407.xlsx", sheet = "map") %>% 
   gather(key="column", value="Sample", `1`:`12`) %>% unite(row, column, col="well", sep="") %>% 
   separate(Sample, into=c("Treatment","Strain"), sep="-", remove = FALSE) %>% drop_na(Treatment) %>% 
   filter(Strain!="Flavo" | is.na(Strain))

# third experiment with flavo too. note there are TYES blanks here.
platedata3 <- readxl::read_xlsx("LoperamideGrowthCurves_20210416.xlsx", 
                                range="A34:AP132", sheet = "data", col_names = FALSE) %>% 
   t(.) %>% as.data.frame() %>% setNames(.[1,]) %>% slice(-1) %>% 
   gather(key="well", value="value", A1:H12) %>% add_column(Assay = "3")

platemap3 <- readxl::read_xlsx("LoperamideGrowthCurves_20210416.xlsx", sheet = "map") %>% 
   gather(key="column", value="Sample", `1`:`12`) %>% unite(row, column, col="well", sep="") %>% 
   separate(Sample, into=c("Treatment","Strain"), sep="-", remove = FALSE) %>% drop_na(Treatment)


# fourth experiment with new strains.
platedata4 <- readxl::read_xlsx("LoperamideGrowthCurves_20220426.xlsx", 
                                range="A34:AT132", sheet="data", col_names = FALSE) %>% 
   t(.) %>% as.data.frame() %>% setNames(.[1,]) %>% slice(-1) %>% 
   pivot_longer(names_to="well", values_to="value", A1:H12) %>% add_column(Assay = "4") %>% 
   filter(!well %in% c("E5","E6","E7","E8","E9","F5","F6","F7","F8","F9"))

platemap4 <- readxl::read_xlsx("LoperamideGrowthCurves_20220426.xlsx", sheet = "map") %>% 
   gather(key="column", value="Sample", `1`:`12`) %>% unite(row, column, col="well", sep="") %>% 
   separate(Sample, into=c("Treatment","Strain"), sep="-", remove = FALSE) %>% drop_na(Treatment) %>% 
   filter(!well %in% c("E5","E6","E7","E8","E9","F5","F6","F7","F8","F9")) %>% 
      filter(!Strain %in% c("Fjohn","Fplur"))


# fifth experiment with new strains.
platedata5 <- readxl::read_xlsx("LoperamideGrowthCurves_20220505.xlsx", 
                                range="A34:AT132", sheet="data", col_names = FALSE) %>% 
   t(.) %>% as.data.frame() %>% setNames(.[1,]) %>% slice(-1) %>% 
   pivot_longer(names_to="well", values_to="value", A1:H12) %>% add_column(Assay = "5") %>% 
   filter(!well %in% c("F6","F7","F8","F9"))

platemap5 <- readxl::read_xlsx("LoperamideGrowthCurves_20220505.xlsx", sheet = "map") %>% 
   gather(key="column", value="Sample", `1`:`12`) %>% unite(row, column, col="well", sep="") %>% 
   separate(Sample, into=c("Treatment","Strain"), sep="-", remove = FALSE) %>% drop_na(Treatment) %>% 
   filter(!well %in% c("F6","F7","F8","F9")) %>% 
   filter(!Strain %in% c("Fjohn","Fplur"))


# sixth experiment with new strains.
platedata6 <- readxl::read_xlsx("LoperamideGrowthCurves_20220518.xlsx", 
                                range="A34:AT132", sheet="data", col_names = FALSE) %>% 
   t(.) %>% as.data.frame() %>% setNames(.[1,]) %>% slice(-1) %>% 
   pivot_longer(names_to="well", values_to="value", A1:H12) %>% add_column(Assay = "6") %>% 
   filter(!well %in% c("E6","E7","E8","E9","F7","F8","F9","F10","F11"))

platemap6 <- readxl::read_xlsx("LoperamideGrowthCurves_20220518.xlsx", sheet = "map") %>% 
   gather(key="column", value="Sample", `1`:`12`) %>% unite(row, column, col="well", sep="") %>% 
   separate(Sample, into=c("Treatment","Strain"), sep="-", remove = FALSE) %>% drop_na(Treatment) %>% 
   filter(!well %in% c("E6","E7","E8","E9","F7","F8","F9","F10","F11")) %>% 
   filter(!Strain %in% c("Fjohn","Fplur"))

# even more new strains
platedata7 <- readxl::read_xlsx("LoperamideGrowthCurves_20220523.xlsx", 
                                range="A34:AT132", sheet="data", col_names = FALSE) %>% 
   t(.) %>% as.data.frame() %>% setNames(.[1,]) %>% slice(-1) %>% 
   pivot_longer(names_to="well", values_to="value", A1:H12) %>% add_column(Assay = "7")

platemap7 <- readxl::read_xlsx("LoperamideGrowthCurves_20220523.xlsx", sheet = "map") %>% 
   gather(key="column", value="Sample", `1`:`12`) %>% unite(row, column, col="well", sep="") %>% 
   separate(Sample, into=c("Treatment","Strain"), sep="-", remove = FALSE) %>% drop_na(Treatment)

straininfo <- readxl::read_xlsx("../../LoperamideStrainInfo.xlsx") %>% 
   mutate(Strain=recode(Strain, "W6"="W6t"))

```


## Data formatting and cleaning

```{r clean, message=FALSE, warning=FALSE}
# join data together
alldata23 <- full_join(platedata2, platemap2) %>% 
   full_join(full_join(platedata3, platemap3)) %>% 
   rename("Time" = `Time [s]`, "Cycle" = `Cycle Nr.`)%>% 
   mutate(value = as.numeric(value)) %>% 
    mutate(Media = case_when(Strain == "Flavo" ~ "TYES", TRUE ~ "LB"))

alldata4567 <- full_join(platedata4, platemap4) %>% 
   full_join(full_join(platedata5, platemap5)) %>% 
   full_join(full_join(platedata6, platemap6)) %>%
   full_join(full_join(platedata7, platemap7)) %>%
   rename("Time" = `Time [s]`, "Cycle" = `Cycle Nr.`) %>% 
   mutate(value = as.numeric(value))

```

### Check the blanks 1,2,3

```{r blanks}

# extract blank data
meanblanks23 <- alldata23 %>% filter(is.na(Strain)) %>% 
   mutate(blankvalue = as.numeric(value)) %>% 
   select(blankvalue, Treatment, Assay) %>% 
   separate(Treatment, into=c("Treatment","Media"), sep="_", remove=FALSE) %>% 
   group_by(Assay, Treatment, Media) %>% 
   summarise(meanblank = mean(blankvalue, rm.na=TRUE)) %>% 
   mutate(Media = replace_na(Media, "LB"))

# add blank data in and subtract based on Treatment and Assay
alldatanorm23 <- alldata23 %>% 
   # fix the TYES labels
   mutate(Treatment = case_when(Treatment == "Con_TYES" ~ "Con", Treatment == "DMSO_TYES" ~ "DMSO",
                                Treatment == "Lop10_TYES" ~ "Lop10", TRUE ~ Treatment)) %>% 
   full_join(meanblanks23) %>% 
   mutate(valuenorm = as.numeric(value) - meanblank) %>% 
   mutate(Treatment = factor(Treatment, labels = c("Control (LB or TYES)", 
                                                   "DMSO 1:20000", "Loperamide 10 mg/L")))
```


### Blanks 4,5,6,7
```{r blanks2}

# extract blank data
blanksclean4567 <- alldata4567 %>% filter(is.na(Strain)) %>% 
   select(Time, value, Treatment, well, Assay) %>% 
   separate(Treatment, into=c("Treatment","Media"), sep="_") %>%
   select(-c(well)) %>% 
   group_by(Treatment, Media, Assay) %>% drop_na() %>% 
   summarise(meanblank = mean(value, rm.na=TRUE))

alldatanorm4567 <- alldata4567 %>% left_join(blanksclean4567) %>% 
   mutate(valuenorm = as.numeric(value) - as.numeric(meanblank)) %>% 
   drop_na(Strain) %>% 
   mutate(Treatment = factor(Treatment, 
                             labels = c("Control (LB or TYES)", "DMSO 1:20000", "Loperamide 10 mg/L"))) 


```

### All together

```{r joins}

alldatanorm <- full_join(alldatanorm23, alldatanorm4567) %>% 
 #  filter(Strain!="W6" & Strain !="W6l")  %>% 
   inner_join(straininfo, by=c("Strain"="Strain")) %>% 
   drop_na(Strain) %>% 
   mutate(CodeName=factor(CodeName, levels=unique(straininfo$CodeName)))
   
alldatanorm %>% 
   distinct(Assay, Strain)

```


```{r alltogether, fig.height=12, fig.width=20, message=FALSE}

alldatanorm %>% unite("AssayTreat", c(Assay, Treatment,well), remove=FALSE) %>% 
   mutate(Time = as.numeric(Cycle)*30/60) %>% filter(Time < 20) %>% 
   mutate(Treatment = factor(Treatment, levels=c("Control (LB or TYES)","DMSO 1:20000", "Loperamide 10 mg/L"),
                             labels = c("Control (LB or TYES)","DMSO 1:10000", "Loperamide 10 mg/L"))) %>% 
   filter(PaperCode %in% c("S1","S3","S4","S5","S6","S7","S8","S9","S10","S2")) %>% 
   mutate(CodeName=recode(CodeName, "S7. *Aeromonas veronii 1*" = "S7. *Aeromonas veronii*")) %>% 
   ggplot(aes(x=Time, y=valuenorm, color=Treatment))+
   stat_summary(aes(lty=Treatment, group=AssayTreat), geom="line", fun="mean", lwd=0.5, alpha=0.2) +
   stat_summary(aes(lty=Treatment), geom="line", fun="mean", lwd=1) +
   facet_wrap(.~CodeName, scales = "free", ncol=3)+
   scale_color_manual(values=c('#000000', '#1c5580', '#0fc08e'))+
   scale_linetype_manual(values = c("solid","dotted","dashed"))+
   guides(color = guide_legend(keywidth = unit(20, units = "mm"), 
                               override.aes = list(lwd = 1.5)))+
   theme(strip.text = element_markdown(size = 20, face="bold"), 
         axis.text = element_text(size=16), 
         axis.title = element_text(size=24), 
         legend.position = c(0.66,0.1), legend.background = element_blank(),
         legend.text = element_text(size=24), legend.key.size = unit(1.2, "cm"),
         panel.grid = element_blank(), panel.grid.major.y = element_blank(),
         plot.background = element_blank(),
         strip.background = element_blank(),
         panel.background = element_rect(size=1, fill="white"))+
   labs(x="Time (hours)", y="OD 600", lty = NULL, color=NULL)

ggsave("FigureS7_GrowthCurvesLoperamide.png", bg = "transparent", width = 15, height=12)
ggsave("FigureS7_GrowthCurvesLoperamide.pdf", bg = "transparent", width = 15, height=12)
ggsave("FigureS7_GrowthCurvesLoperamide.tiff", bg = "transparent", width = 15, height=12)

```

```{r, fig.width=20}


alldatanorm %>% unite("AssayTreat", c(Assay, Treatment,well), remove=FALSE) %>% 
   mutate(Time = as.numeric(Cycle)*30/60) %>% filter(Time < 20) %>% 
   mutate(Treatment = factor(Treatment, levels=c("Control (LB or TYES)","DMSO 1:20000", "Loperamide 10 mg/L"),
                             labels = c("Control","DMSO", "Loperamide"))) %>% 
   filter(PaperCode %in% c("S1","S4","S5","S7","S8","S9","S10","S2")) %>% 
   mutate(CodeName=recode(CodeName, "S7. *Aeromonas veronii 1*" = "S7. *Aeromonas veronii*")) %>% 
   mutate(PaperName=factor(PaperName, levels=c("Pseudomonas mossellii","Variovorax gossypii",
                                               "Achromobacter marplatensis","Stenotrophomas maltophilia",
                                               "Aeromonas veronii","Rhizobium sp.",
                                               "Ochrobactrum tritici","Flavobacterium johnsoniae"))) %>% 
   ggplot(aes(x=Time, y=valuenorm, color=Treatment))+
   stat_summary(aes(lty=Treatment, group=AssayTreat), geom="line", fun="mean", lwd=0.5, alpha=0.4) +
   stat_summary(aes(lty=Treatment), geom="line", fun="mean", lwd=2) +
   facet_wrap(.~PaperName, scales = "free", ncol=4)+
   scale_color_manual(values=c('white', 'dodgerblue', '#0fc08e'))+
   scale_linetype_manual(values = c("solid","dotted","dashed"))+
   guides(color = guide_legend(keywidth = unit(20, units = "mm"), 
                               override.aes = list(lwd = 1.5)))+
   theme(legend.position="top", text=element_text(color="white", family="Avenir"),
         plot.background = element_blank(),
         panel.background = element_rect(fill="grey15", color="transparent"),
         axis.text=element_text(color="white", size=16),
         axis.title = element_text(face="bold", size=24),
         legend.background = element_blank(),
         legend.text = element_text(size=24), legend.key.size = unit(1.2, "cm"),
         strip.text = element_markdown(size = 20, color="white", face="italic"), 
         axis.ticks = element_line(color="white"), axis.line = element_line(color="white"),
         strip.background = element_blank(),
         panel.grid = element_blank(), panel.grid.major.y = element_blank())+
   labs(x="Time (hours)", y="OD 600", lty = NULL, color=NULL)

ggsave("FigureS7_GrowthCurvesLoperamide_bw.png", bg = "transparent", width = 18, height=7)


```

```{r session}

sessionInfo()

```
